spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13306/test?serverTimezone=Asia/Seoul
    username: root
    password: root

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
        dialect: org.hibernate.dialect.MySQLDialect
    logging:
      level:
        org.hibernate.SQL: info


  data:
    redis:
      host: localhost
      port: 6379
