spring:
  application:
    name: pay-separately
  h2:
    console:
      enabled: true
      path: /h2-console
    datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:~/pay-separately
      username: sa
      password:
    jpa:
      show_sql: true
      hibernate:
        ddl-auto: create

